server:
  port: 8080

bookdemo:
  param1: Das ist ein Test
  nested:
    param3: Param3
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookdemo
    username: user
    password: pass
    hikari:
      pool-name: my-pool
  jpa:
    hibernate:
      ddl-auto: 

  h2:
    console:
      enabled: true
      
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/changelog.xml      
        
---

spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8090
